version: 2

updates:
  # Java / Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:

      interval: "daily"




  # Docker base image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

