name: Order Service CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn --version

      - name: Build and test
        run: mvn clean verify
