name: Order Service CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Display Java version
        run: java -version

      - name: Build application
        run: mvn clean package

      - name: Run tests
        run: mvn test
